DROP TABLE IF EXISTS ROBOTPATH;

CREATE TABLE ROBOTPATH(ID int NOT NULL AUTO_INCREMENT,
   INITIALPOS VARCHAR(255),
   FINALPOS VARCHAR(255),
   MOVEMENT VARCHAR(255),
   LOST CHAR,
   DATE TIMESTAMP(8)
);


DROP TABLE IF EXISTS ROBOTDANGERPOINTS;

CREATE TABLE ROBOTDANGERPOINTS(ID int NOT NULL AUTO_INCREMENT,
   COORDX VARCHAR(255),
   COORDY VARCHAR(255),
   DATE TIMESTAMP(8)
);